import PlayAudio from './Audio'

export default function playSoundByAction(action) {
  if (action.includes("peach")) PlayAudio.heal()
  else if (action.includes("dodge")) PlayAudio.reflect()
  else if (action.includes("barbarian")) PlayAudio.warCry()
  else if (action.includes("raining_arrows")) PlayAudio.bow()
  else if (action.includes("steal")) PlayAudio.sheep()
  else if (action.includes("attack_by_fire")) PlayAudio.move4()
  else if (action.includes("attack")) PlayAudio.attack()
  else if (action.includes("negation")) PlayAudio.skillSuccess()
  else if (action.includes("lightning")) PlayAudio.thunder()
  else if (action.includes("burn_bridge")) PlayAudio.broken()
  else if (action.includes("harvest")) PlayAudio.harvest()
  else if (action.includes("brotherhood")) PlayAudio.cheer()
  else if (action.includes("greed")) PlayAudio.greed()
  else if (action.includes("acedia")) PlayAudio.fire()
  else if (action.includes("borrowed_sword")) PlayAudio.sword()
  else if (action.includes("horse_atk")) PlayAudio.equipHorse()
  else if (action.includes("horse_def")) PlayAudio.equipHorse()
  else if (action.includes("equip_item")) PlayAudio.equipItem()
  else if (action.includes("weapon")) PlayAudio.equipItem()
  else if (action.includes("wine")) PlayAudio.drinking()
  else if (action.includes("rest")) PlayAudio.marchDrum()
  else if (action.includes("ration")) PlayAudio.ice2()
  else if (action.includes("duel")) PlayAudio.duel()
  else if (action.includes("chain")) PlayAudio.chain()
  else if (action.includes("carrier")) PlayAudio.cow()
  else if (action.includes("alliance")) PlayAudio.fanfare()
  else if (action.includes("know_enemy")) PlayAudio.shock()
  else if (action.includes("trick_state")) PlayAudio.confuse()
}
